### PR TITLE
Add types for Draggable isActive and Droppable willAccept params

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by TrySound** [comment]
Congrats with 100 stars

**Comment by chrisjpatty** [comment]
Thanks! And thanks for all your pull requests, they've been invaluable!

**Comment by TrySound** [comment]
Can you ping me when you add new features? I can skip something

**Comment by chrisjpatty** [comment]
Yeah totally. What's the best way for me to message you? If I tag you in commits that have new features will that notify you?

**Comment by TrySound** [comment]
@chrisjpatty I mean it would be better to keep types in sync before every release. You can send me PM in twitter or you can open PRs for features.

**Comment by TrySound** [comment]
PRs will also be good for users

**Comment by chrisjpatty** [comment]
Good idea, I'll start branching off and creating PRs with new features going forward. What's your Twitter username?

**Comment by TrySound** [comment]
[IAmTrySound](https://twitter.com/IAmTrySound)

**Pull request merged**
