### PR TITLE
Build with rollup

### PR DESCRIPTION
**Pull request by TrySound**
Here's results for comparison

webpack
build/index.js 74.84K
build/index.min.js 48.45K

rollup
build/index.js 14.50K
build/index.min.js 11.52K

### CODE REVIEW

**Comment by chrisjpatty** [comment]
Hey thanks for the pull request! At the moment I'm not super familiar with rollup other than a casual understanding that it's an alternative to Webpack aimed at libraries. This looks like a huge size reduction in the distributable, help me understand what Rollup is doing to cut down the size so dramatically.

**Comment by TrySound** [comment]
Hi. Rollup uses scope hoisting which allows to get rid from wrappers around every module. Its babel plugin able to deduplicate helpers. Also rollup do not add runtime at the top.

**Comment by TrySound** [comment]
Also webpack adds process polyfill.

**Comment by TrySound** [comment]
And I removed shortid from bundle.

**Comment by chrisjpatty** [comment]
Definitely open to this change. Does moving to Rollup affect the package at all in terms of browser compatibility?

**Comment by TrySound** [comment]
Nope, it's the same commonjs output. I also added es output to let both webpack and rollup pack this module nicer in user land.

**Comment by chrisjpatty** [comment]
Awesome! Well this looks great then. I'm away from my computer at the moment, but I'll pull down the changes tomorrow into my test environment and then if everything looks great I'll merge it in. Thanks again for the pull request! I'll definitely have to look into using Rollup for some of my other projects too.

**Pull request merged**
