### PR TITLE
Refactor store

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by chrisjpatty** [comment]
Help me understand this change, does this improve performance? It looks like this would introduce memory leaks where the store could be attempting to broadcast to a component that is no longer mounted. The idea original is similar to Redux where a unique id is used to allow each component to unsubscribe before unmounting. With this change does each component still unsubscribe itself?

**Comment by TrySound** [comment]
Yep. But instead of id we use callback reference [here](https://github.com/chrisjpatty/react-dragtastic/pull/15/files#diff-3bf35cd41da51153dcca3003656f7c67R31)

**Comment by TrySound** [comment]
You didn't used unsubscribe method before

**Comment by chrisjpatty** [comment]
Ah, I see now. Clever, I hadn't thought to handle it this way. This is a core change so when I get a minute I'll pull it down and run some tests, but if everything looks good I'll try to get it merged in later today. Thanks!

**Comment by TrySound** [comment]
Could you add me to collaborators? I'll still will open PRs, but with a bit less mess in branches.

**Comment by chrisjpatty** [comment]
Yeah sure, as long as you open pull requests I'll add you as a collaborator.

**Pull request merged**
