### PR TITLE
Typescript types

### PR DESCRIPTION
**Pull request by nscarcella**
See #33.

I also updated the build script to include the copy of these types. Please let me know if you see something is off or if you want me to make some other change (like a minor version bump).

### CODE REVIEW

**Comment by nscarcella** [comment]
Uhm... weird. Test seem to be passing but the exitcode is still 1. Seems to also be happening on master. Is this normal?

**Comment by chrisjpatty** [comment]
Our tests seem to pass or fail somewhat unpredictably. I'll pull it down and test just to verify but I would imagine it's probably fine. Thanks for the pull request!

**Comment by nscarcella** [comment]
@chrisjpatty Ok, let me know if any changes are necessary.

**Comment by chrisjpatty** [comment]
Sorry I'm just getting around to this. Thanks for contributing!

**Pull request merged**
